[package]
name = "opensound"
authors = ["29 <791603901@qq.com>"]
version = "0.0.1"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["audio", "midi", "music", "sound", "daw"]
categories = ["multimedia", "multimedia::audio"]
repository = "https://gitlab.com/opensound-org/opensound"
homepage = "https://opensound.run"
documentation = "https://docs.rs/opensound"
description = """
OpenSound API Server.
"""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.35", features = ["serde"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["chrono"] }
