[package]
name = "opensound"
authors = ["29 <791603901@qq.com>"]
version = "0.0.6"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["audio", "midi", "music", "sound", "daw"]
categories = [
    "multimedia",
    "multimedia::audio",
    "network-programming",
    "web-programming::http-server",
    "web-programming::websocket"
]
repository = "https://gitlab.com/opensound-org/opensound"
homepage = "https://opensound.run"
documentation = "https://docs.rs/opensound"
description = """
(WIP)A One-Stop Multi-Level SoundSystem Abstraction (or say sound/audio engine). Suitable for being a solid foundation for Pro-Audio Applications(e.g. a DAW) or other sound related apps.
"""
edition = "2021"
rust-version = "1.64.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.35", features = ["serde"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["chrono"] }
