on: [push, workflow_dispatch]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: yesolutions/mirror-action@master
      with:
        REMOTE: 'https://gitea.29bot.com/opensound-org/opensound.git'
        REMOTE_NAME: gitea
        GIT_USERNAME: 29bot
        GIT_PASSWORD: ${{ secrets.GITEA_PASSWORD }}
    - uses: yesolutions/mirror-action@master
      with:
        REMOTE: 'https://gitee.com/opensound-org/opensound.git'
        REMOTE_NAME: gitee
        GIT_USERNAME: czy29
        GIT_PASSWORD: ${{ secrets.GITEE_PASSWORD }}
